/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/Sqp9sqEU5na
 * Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
 */

/** Add fonts into your Next.js project:

import { Archivo } from 'next/font/google'

archivo({
  subsets: ['latin'],
  display: 'swap',
})

To read more about using these font, please visit the Next.js documentation:
- App Directory: https://nextjs.org/docs/app/building-your-application/optimizing/fonts
- Pages Directory: https://nextjs.org/docs/pages/building-your-application/optimizing/fonts
**/
//props

import { collection, getDocs } from "firebase/firestore";
import { useQuery } from "@tanstack/react-query";
import { db } from "@/utils/firebase";

function ActivityCard({
  title,
  date,
  subtitle,
}: {
  title: string;
  date: Date;
  subtitle: string;
}) {
  return (
    <div className="grid gap-2 text-sm relative">
      <div className="aspect-square w-3 bg-primary rounded-full absolute left-0 translate-x-[-29.5px] z-10 top-1" />
      <div className="font-medium">{title}</div>
      <div className="text-muted-foreground">
        <div className="flex items-center gap-2">
          <CalendarIcon className="w-4 h-4" />
          <span>{date.toString()}</span>
        </div>
        <p>{subtitle}</p>
      </div>
    </div>
  );
}

export function ActivityOverview() {
  const { data } = useQuery({
    queryKey: ["getActivities"],
    queryFn: () => getDocs(collection(db, "activities")),
  });

  return (
    <div className="w-full max-w-4xl mx-auto py-12 md:py-20">
      <div className="space-y-4 text-center">
        <h2 className="text-3xl font-bold tracking-tighter sm:text-4xl">
          Activity Timeline
        </h2>
        <p className="text-muted-foreground md:text-lg">
          Stay up to date with the latest activities and milestones in your
          organization.
        </p>
      </div>
      <div className="mt-12 space-y-8">
        <div className="after:absolute after:inset-y-0 after:w-px after:bg-muted-foreground/20 relative pl-6 after:left-0 grid gap-8">
          {data?.docs
            .map((doc) => doc.data())
            .map((docData) => (
              <ActivityCard
                title={docData.title}
                date={docData.date.toDate()}
                subtitle={docData.subtitle}
              />
            ))}
        </div>
      </div>
    </div>
  );
}

function CalendarIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M8 2v4" />
      <path d="M16 2v4" />
      <rect width="18" height="18" x="3" y="4" rx="2" />
      <path d="M3 10h18" />
    </svg>
  );
}
